spring:
  application:
    name: coin-mestre
  sql:
    init:
      platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
